In [3]:
# Import libraries 
import numpy as np 
import pandas as pd 
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#from sklearn.metrics import jaccard_similarity_score

from sklearn.model_selection import train_test_split

# Import dataset 
df = pd.read_csv('data/Processed data.csv')  

In [4]:
df.head(10)

Day  Month  Airline flightclass  capacity  timediff  night1  season  \
0    4      0        1         INT         0       -17       0  Summer   
1    3      0        1         INT        36       -25       0  Summer   
2    3      0        1         INT        19        -5       0  Summer   
3    5      0        1         INT        33       -31       0  Summer   
4    5      0        1         DOM         0         2       0  Summer   
5    3      7        1         INT        21       -22       0  Summer   
6    5      7        1         INT         0       -19       0  Summer   
7    5      7        1         DOM         0       -43       0  Summer   
8    4      7        1         INT         0        62       0  Summer   
9    2      7        1         INT         0       -13       0  Summer   

   delayed  
0        0  
1        0  
2        0  
3        0  
4        0  
5        0  
6        0  
7        0  
8        1  
9        0

In [5]:
columns= ['flightclass','season',]
le=LabelEncoder()
for i in columns:
     df[i]=le.fit_transform(df[i])

In [6]:
df['Airline'].unique()

array([ 1,  2,  3,  4,  6,  5,  7,  8,  9, 10, 11, 12, 14, 15, 16, 18, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33,  0, 13, 17, 19, 30],
      dtype=int64)

In [37]:
df['season'].unique()

array([0, 1])

In [38]:
df['flightclass'].unique()

array([1, 0])

In [8]:
X = df.iloc[:, 0:6].values # from column(years) to column(distance)
X[0:5]

array([[  4,   0,   1,   1,   0, -17],
       [  3,   0,   1,   1,  36, -25],
       [  3,   0,   1,   1,  19,  -5],
       [  5,   0,   1,   1,  33, -31],
       [  5,   0,   1,   0,   0,   2]], dtype=int64)

In [9]:
y = df['delayed']
y.head().to_frame()

delayed
0        0
1        0
2        0
3        0
4        0

In [41]:
for i in range(0, 20):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=i)
    
    #creating random forest classifier
    clf = RandomForestClassifier(random_state=i)
    clf.fit(X_train, y_train)
    
    #determining the score
    train_score = clf.score(X_train, y_train)
    test_score = clf.score(X_test, y_test)
    print("Test: {}, Train: {} and Random State: {}".format(test_score, train_score, i))

Test: 1.0, Train: 1.0 and Random State: 0
Test: 1.0, Train: 1.0 and Random State: 1
Test: 1.0, Train: 1.0 and Random State: 2
Test: 1.0, Train: 1.0 and Random State: 3
Test: 1.0, Train: 1.0 and Random State: 4
Test: 1.0, Train: 1.0 and Random State: 5
Test: 1.0, Train: 1.0 and Random State: 6
Test: 1.0, Train: 1.0 and Random State: 7
Test: 1.0, Train: 1.0 and Random State: 8
Test: 1.0, Train: 1.0 and Random State: 9
Test: 1.0, Train: 1.0 and Random State: 10
Test: 1.0, Train: 1.0 and Random State: 11
Test: 1.0, Train: 1.0 and Random State: 12
Test: 1.0, Train: 1.0 and Random State: 13
Test: 1.0, Train: 1.0 and Random State: 14
Test: 1.0, Train: 1.0 and Random State: 15
Test: 1.0, Train: 1.0 and Random State: 16
Test: 1.0, Train: 1.0 and Random State: 17
Test: 1.0, Train: 1.0 and Random State: 18
Test: 1.0, Train: 1.0 and Random State: 19


In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=18)
clf = RandomForestClassifier(random_state=18)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=18)

In [43]:
print("Train set: ", clf.score(X_train, y_train))

Train set:  1.0


In [44]:
print("Test set: ", clf.score(X_test, y_test))

Test set:  1.0


In [45]:
# predicting the trained Classifier to the test
yhat = clf.predict(X_test)

In [46]:
# Viewing the predicted probabilities of first 10 observations
yhat_prob = clf.predict_proba(X_test)[:10]

In [47]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1818
           1       1.00      1.00      1.00      3191

    accuracy                           1.00      5009
   macro avg       1.00      1.00      1.00      5009
weighted avg       1.00      1.00      1.00      5009



In [48]:
# Saving model to disk
pickle.dump(clf,open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))